### ISSUE TITLE
Template Sensor wird nicht angezeigt

### ISSUE THREAD

**Issue by svenschedlbauer** [MaxxKra/Abfallerinnerung#1]
Bei mir werden leider die Template Sensoren "mullabholung_heute" und "mullabholung_text" nicht angezeigt. Die Daten habe ich in meine configuration.yaml eingetragen und ich bekomme keine Fehler angezeigt... Woran könnte das liegen?

Wie kann ich kontrollieren, ob die Frontend Sachen korrekt installiert wurden. Bei mir passt am Ende leider auch nicht die Schriftgröße und das Popup-Fenster öffnet sich auch nicht... Irgendwo hänge ich und komme nicht weiter :-(

![image](https://github.com/MaxxKra/Abfallerinnerung/assets/110197932/dcf101a7-02e9-405e-90e2-a94d601465f7)

Hoffe jmd kann mir hier weiterhelfen.

**Comment by MaxxKra** [comment]
Wenn du den Template Sensor direkt in der "configuration.yaml" geschrieben hast, gehe ich von einem Tabulator Fehler aus.

Ein grundlegender Code für die Einbindung der Templates in die configuration.yaml sollte in etwa so aussehen:

```yaml
###---- Template Müllabholung Heute ----###
template:
  - sensor:
      - name: Müllabholung Heute
        unique_id: mullabholung_heute
        icon: mdi:trash-can-outline
        state: >
          {% set ALTPAPIER = states.sensor.altpapier.state %}
          {% set LEICHTVERPACKUNG = states.sensor.leichtverpackung.state %}
          {% set RESTABFALL = states.sensor.restabfall.state %}
          {% set BIOABFALL = states.sensor.bioabfall.state %}
          {% if ALTPAPIER == "Heute" and LEICHTVERPACKUNG == "Heute" and RESTABFALL == "Heute" and BIOABFALL == "Heute" %}
          die Altpapier, Leichtverpackung, Restabfall und Bioabfall
          {% elif LEICHTVERPACKUNG == "Heute" and RESTABFALL == "Heute" and BIOABFALL == "Heute" %}
          die Leichtverpackung, Restabfall und Bioabfall
          {% elif ALTPAPIER == "Heute" and RESTABFALL == "Heute" and BIOABFALL == "Heute" %}
          die Altpapier, Restabfall und Bioabfall
          {% elif ALTPAPIER == "Heute" and LEICHTVERPACKUNG == "Heute" and BIOABFALL == "Heute" %}
          die Altpapier, Leichtverpackung und Bioabfall
          {% elif ALTPAPIER == "Heute" and LEICHTVERPACKUNG == "Heute" and RESTABFALL == "Heute" %}
          die Altpapier, Leichtverpackung und Restabfall
          {% elif ALTPAPIER == "Heute" and LEICHTVERPACKUNG == "Heute" %}
          die Altpapier und Leichtverpackung
          {% elif ALTPAPIER == "Heute" and RESTABFALL == "Heute" %}
          die Altpapier und Restabfall
          {% elif ALTPAPIER == "Heute" and BIOABFALL == "Heute" %}
          die Altpapier und Bioabfall
          {% elif LEICHTVERPACKUNG == "Heute" and RESTABFALL == "Heute" %}
          die Leichtverpackung und Restabfall
          {% elif LEICHTVERPACKUNG == "Heute" and BIOABFALL == "Heute" %}
          die Leichtverpackung und Bioabfall
          {% elif RESTABFALL == "Heute" and BIOABFALL == "Heute" %}
          die Restabfall und Bioabfall
          {% elif ALTPAPIER == "Heute" %}
          die Altpapier
          {% elif LEICHTVERPACKUNG == "Heute" %}
          die Leichtverpackung
          {% elif RESTABFALL == "Heute" %}
          die Restabfall
          {% elif BIOABFALL == "Heute" %}
          die Bioabfall
          {% else %}
          keine
          {%endif%}

###---- Template Müllabholung Text ----###
      - name: Müllabholung Text
        unique_id: mullabholung_text
        icon: mdi:trash-can-outline
        state: >
          {% if states.sensor.mullabholung_heute.state != 'keine' %}
          Du musst heute {{ states.sensor.mullabholung_heute.state }} Tonne rausstellen!
          {% else %}
          
          {%endif%}
```

Was die Frontend Karten und Integrationen sowie die Popup Karte betrifft, ist wichtig, dass alle Tools wie Browser_Mod, Custom Button Card oder Card_Mod installiert und eingerichtet sind.

Eine gute Hilfestellung für die ganze Müllerinnerung ist das EXCEL File als Code Generator. Mit diesem lassen sich Schriftgrößen, Namen und allgemeine Einstellungen einfach anpassen und dann unkompliziert kopieren und einfügen.
Die EXCEL Datei erhällst du per Mail auf Anfrage unter: youtube@smarthomebastler.at

**Comment by svenschedlbauer** [comment]
Vielen Dank. Es war wirklich die Einrückung. Warum auch immer musste ich bei mir die Punkte nach state: > um weitere zwei Leerzeilen einrücken. Jetzt sieht es gut aus, bis auf das Popup, was noch nicht funktioniert. Werde mal ne Mail senden, danke :-)
Grüße Sven
